[package]
name = "pwd-crabager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "4.0.0"
rand = "0.8.5"
pickledb = "0.5.1"
structopt = "0.3.26"